# ============================================
# ssm-grafana-kafka-dashboard.tf
# SSM Document to create MSK Kafka dashboard
# ============================================

resource "aws_ssm_document" "grafana_kafka_dashboard" {
  name            = "${lower(local.effective_tenant)}-${local.primary_env}-grafana-kafka-dashboard"
  document_type   = "Command"
  document_format = "YAML"

  content = yamlencode({
    schemaVersion = "2.2"
    description   = "Configure self-hosted Grafana with MSK Kafka monitoring dashboard"
    parameters = {
      Region = {
        type        = "String"
        description = "AWS Region"
        default     = local.effective_region
      }
      ClusterName = {
        type        = "String"
        description = "EKS Cluster Name"
      }
    }
    mainSteps = [
      {
        action = "aws:runShellScript"
        name   = "configureKafkaDashboard"
        inputs = {
          runCommand = [
            "#!/bin/bash",
            "set -e",
            "",
            "CLUSTER_NAME='{{ ClusterName }}'",
            "REGION='{{ Region }}'",
            "",
            "export HOME=/root",
            "export KUBECONFIG=/root/.kube/config",
            "export AWS_REGION=\"$REGION\" AWS_DEFAULT_REGION=\"$REGION\"",
            "",
            "echo \"[Grafana] Configuring MSK Kafka dashboard in self-hosted Grafana\"",
            "",
            "aws eks update-kubeconfig --name \"$CLUSTER_NAME\" --region \"$REGION\" --kubeconfig \"$KUBECONFIG\"",
            "",
            "POD_NAME=$(kubectl get pods -n monitoring -l app.kubernetes.io/name=grafana -o jsonpath='{.items[0].metadata.name}')",
            "if [ -z \"$POD_NAME\" ]; then",
            "  echo \"[ERROR] Grafana pod not found\"",
            "  exit 1",
            "fi",
            "",
            "echo \"[Grafana] Found Grafana pod: $POD_NAME\"",
            "",
            "GRAFANA_PASSWORD=$(kubectl get secret -n monitoring prometheus-grafana -o jsonpath='{.data.admin-password}' | base64 -d)",
            "",
            "echo \"[Grafana] Port-forwarding to Grafana (background)\"",
            "kubectl port-forward -n monitoring \"$POD_NAME\" 3000:3000 &",
            "PF_PID=$!",
            "sleep 5",
            "",
            "API_URL='http://localhost:3000/api'",
            "",
            "echo \"[Grafana] Creating MSK Kafka Monitoring dashboard\"",
            "cat > /tmp/kafka-dashboard.json <<'DASH_EOF'",
            "{",
            "  \"dashboard\": {",
            "    \"title\": \"MSK Kafka Monitoring\",",
            "    \"tags\": [\"kafka\", \"msk\", \"messaging\"],",
            "    \"timezone\": \"browser\",",
            "    \"schemaVersion\": 16,",
            "    \"version\": 0,",
            "    \"refresh\": \"30s\",",
            "    \"panels\": [",
            "      {",
            "        \"type\": \"row\",",
            "        \"title\": \"Throughput Metrics\",",
            "        \"gridPos\": {\"x\": 0, \"y\": 0, \"w\": 24, \"h\": 1},",
            "        \"collapsed\": false",
            "      },",
            "      {",
            "        \"type\": \"timeseries\",",
            "        \"title\": \"Bytes In Per Second\",",
            "        \"gridPos\": {\"x\": 0, \"y\": 1, \"w\": 12, \"h\": 8},",
            "        \"targets\": [{",
            "          \"expr\": \"aws_kafka_bytes_in_per_sec_average\",",
            "          \"refId\": \"A\",",
            "          \"legendFormat\": \"{{name}}\"",
            "        }],",
            "        \"options\": {\"legend\": {\"displayMode\": \"table\", \"placement\": \"bottom\"}},",
            "        \"fieldConfig\": {",
            "          \"defaults\": {",
            "            \"unit\": \"Bps\",",
            "            \"color\": {\"mode\": \"palette-classic\"}",
            "          }",
            "        }",
            "      },",
            "      {",
            "        \"type\": \"timeseries\",",
            "        \"title\": \"Bytes Out Per Second\",",
            "        \"gridPos\": {\"x\": 12, \"y\": 1, \"w\": 12, \"h\": 8},",
            "        \"targets\": [{",
            "          \"expr\": \"aws_kafka_bytes_out_per_sec_average\",",
            "          \"refId\": \"A\",",
            "          \"legendFormat\": \"{{name}}\"",
            "        }],",
            "        \"options\": {\"legend\": {\"displayMode\": \"table\", \"placement\": \"bottom\"}},",
            "        \"fieldConfig\": {",
            "          \"defaults\": {",
            "            \"unit\": \"Bps\",",
            "            \"color\": {\"mode\": \"palette-classic\"}",
            "          }",
            "        }",
            "      },",
            "      {",
            "        \"type\": \"stat\",",
            "        \"title\": \"Total Messages In/Sec\",",
            "        \"gridPos\": {\"x\": 0, \"y\": 9, \"w\": 8, \"h\": 4},",
            "        \"targets\": [{",
            "          \"expr\": \"sum(aws_kafka_messages_in_per_sec_sum)\",",
            "          \"refId\": \"A\"",
            "        }],",
            "        \"options\": {\"graphMode\": \"area\", \"colorMode\": \"value\"},",
            "        \"fieldConfig\": {",
            "          \"defaults\": {",
            "            \"unit\": \"short\",",
            "            \"thresholds\": {",
            "              \"mode\": \"absolute\",",
            "              \"steps\": [",
            "                {\"value\": 0, \"color\": \"green\"},",
            "                {\"value\": 10000, \"color\": \"yellow\"},",
            "                {\"value\": 50000, \"color\": \"red\"}",
            "              ]",
            "            }",
            "          }",
            "        }",
            "      },",
            "      {",
            "        \"type\": \"timeseries\",",
            "        \"title\": \"Messages In Per Second by Cluster\",",
            "        \"gridPos\": {\"x\": 8, \"y\": 9, \"w\": 16, \"h\": 8},",
            "        \"targets\": [{",
            "          \"expr\": \"aws_kafka_messages_in_per_sec_average\",",
            "          \"refId\": \"A\",",
            "          \"legendFormat\": \"{{name}}\"",
            "        }],",
            "        \"options\": {\"legend\": {\"displayMode\": \"table\", \"placement\": \"bottom\"}},",
            "        \"fieldConfig\": {",
            "          \"defaults\": {",
            "            \"unit\": \"short\",",
            "            \"color\": {\"mode\": \"palette-classic\"}",
            "          }",
            "        }",
            "      },",
            "      {",
            "        \"type\": \"row\",",
            "        \"title\": \"Resource Usage\",",
            "        \"gridPos\": {\"x\": 0, \"y\": 17, \"w\": 24, \"h\": 1},",
            "        \"collapsed\": false",
            "      },",
            "      {",
            "        \"type\": \"timeseries\",",
            "        \"title\": \"CPU User %\",",
            "        \"gridPos\": {\"x\": 0, \"y\": 18, \"w\": 8, \"h\": 8},",
            "        \"targets\": [{",
            "          \"expr\": \"aws_kafka_cpu_user_average\",",
            "          \"refId\": \"A\",",
            "          \"legendFormat\": \"{{name}}\"",
            "        }],",
            "        \"options\": {\"legend\": {\"displayMode\": \"list\", \"placement\": \"bottom\"}},",
            "        \"fieldConfig\": {",
            "          \"defaults\": {",
            "            \"unit\": \"percent\",",
            "            \"min\": 0,",
            "            \"max\": 100,",
            "            \"color\": {\"mode\": \"palette-classic\"},",
            "            \"thresholds\": {",
            "              \"mode\": \"absolute\",",
            "              \"steps\": [",
            "                {\"value\": 0, \"color\": \"green\"},",
            "                {\"value\": 70, \"color\": \"yellow\"},",
            "                {\"value\": 85, \"color\": \"red\"}",
            "              ]",
            "            }",
            "          }",
            "        }",
            "      },",
            "      {",
            "        \"type\": \"timeseries\",",
            "        \"title\": \"CPU System %\",",
            "        \"gridPos\": {\"x\": 8, \"y\": 18, \"w\": 8, \"h\": 8},",
            "        \"targets\": [{",
            "          \"expr\": \"aws_kafka_cpu_system_average\",",
            "          \"refId\": \"A\",",
            "          \"legendFormat\": \"{{name}}\"",
            "        }],",
            "        \"options\": {\"legend\": {\"displayMode\": \"list\", \"placement\": \"bottom\"}},",
            "        \"fieldConfig\": {",
            "          \"defaults\": {",
            "            \"unit\": \"percent\",",
            "            \"min\": 0,",
            "            \"max\": 100,",
            "            \"color\": {\"mode\": \"palette-classic\"},",
            "            \"thresholds\": {",
            "              \"mode\": \"absolute\",",
            "              \"steps\": [",
            "                {\"value\": 0, \"color\": \"green\"},",
            "                {\"value\": 70, \"color\": \"yellow\"},",
            "                {\"value\": 85, \"color\": \"red\"}",
            "              ]",
            "            }",
            "          }",
            "        }",
            "      },",
            "      {",
            "        \"type\": \"timeseries\",",
            "        \"title\": \"Memory Used\",",
            "        \"gridPos\": {\"x\": 16, \"y\": 18, \"w\": 8, \"h\": 8},",
            "        \"targets\": [{",
            "          \"expr\": \"aws_kafka_memory_used_average / 1024 / 1024 / 1024\",",
            "          \"refId\": \"A\",",
            "          \"legendFormat\": \"{{name}}\"",
            "        }],",
            "        \"options\": {\"legend\": {\"displayMode\": \"list\", \"placement\": \"bottom\"}},",
            "        \"fieldConfig\": {",
            "          \"defaults\": {",
            "            \"unit\": \"decgbytes\",",
            "            \"color\": {\"mode\": \"palette-classic\"}",
            "          }",
            "        }",
            "      },",
            "      {",
            "        \"type\": \"timeseries\",",
            "        \"title\": \"Kafka Data Logs Disk Used %\",",
            "        \"gridPos\": {\"x\": 0, \"y\": 26, \"w\": 12, \"h\": 8},",
            "        \"targets\": [{",
            "          \"expr\": \"aws_kafka_kafka_data_logs_disk_used_average\",",
            "          \"refId\": \"A\",",
            "          \"legendFormat\": \"{{name}}\"",
            "        }],",
            "        \"options\": {\"legend\": {\"displayMode\": \"table\", \"placement\": \"bottom\"}},",
            "        \"fieldConfig\": {",
            "          \"defaults\": {",
            "            \"unit\": \"percent\",",
            "            \"min\": 0,",
            "            \"max\": 100,",
            "            \"color\": {\"mode\": \"thresholds\"},",
            "            \"thresholds\": {",
            "              \"mode\": \"absolute\",",
            "              \"steps\": [",
            "                {\"value\": 0, \"color\": \"green\"},",
            "                {\"value\": 70, \"color\": \"yellow\"},",
            "                {\"value\": 85, \"color\": \"red\"}",
            "              ]",
            "            }",
            "          }",
            "        }",
            "      },",
            "      {",
            "        \"type\": \"stat\",",
            "        \"title\": \"Current Disk Usage\",",
            "        \"gridPos\": {\"x\": 12, \"y\": 26, \"w\": 6, \"h\": 4},",
            "        \"targets\": [{",
            "          \"expr\": \"aws_kafka_kafka_data_logs_disk_used_maximum\",",
            "          \"refId\": \"A\"",
            "        }],",
            "        \"options\": {\"graphMode\": \"area\", \"colorMode\": \"value\"},",
            "        \"fieldConfig\": {",
            "          \"defaults\": {",
            "            \"unit\": \"percent\",",
            "            \"thresholds\": {",
            "              \"mode\": \"absolute\",",
            "              \"steps\": [",
            "                {\"value\": 0, \"color\": \"green\"},",
            "                {\"value\": 70, \"color\": \"yellow\"},",
            "                {\"value\": 85, \"color\": \"red\"}",
            "              ]",
            "            }",
            "          }",
            "        }",
            "      },",
            "      {",
            "        \"type\": \"row\",",
            "        \"title\": \"Performance Metrics\",",
            "        \"gridPos\": {\"x\": 0, \"y\": 34, \"w\": 24, \"h\": 1},",
            "        \"collapsed\": false",
            "      },",
            "      {",
            "        \"type\": \"timeseries\",",
            "        \"title\": \"Fetch Consumer Total Time (ms)\",",
            "        \"gridPos\": {\"x\": 0, \"y\": 35, \"w\": 12, \"h\": 8},",
            "        \"targets\": [{",
            "          \"expr\": \"aws_kafka_fetch_consumer_total_time_ms_average\",",
            "          \"refId\": \"A\",",
            "          \"legendFormat\": \"{{name}} - avg\"",
            "        }, {",
            "          \"expr\": \"aws_kafka_fetch_consumer_total_time_ms_maximum\",",
            "          \"refId\": \"B\",",
            "          \"legendFormat\": \"{{name}} - max\"",
            "        }],",
            "        \"options\": {\"legend\": {\"displayMode\": \"table\", \"placement\": \"bottom\"}},",
            "        \"fieldConfig\": {",
            "          \"defaults\": {",
            "            \"unit\": \"ms\",",
            "            \"color\": {\"mode\": \"palette-classic\"}",
            "          }",
            "        }",
            "      },",
            "      {",
            "        \"type\": \"timeseries\",",
            "        \"title\": \"Produce Message Conversions Time (ms)\",",
            "        \"gridPos\": {\"x\": 12, \"y\": 35, \"w\": 12, \"h\": 8},",
            "        \"targets\": [{",
            "          \"expr\": \"aws_kafka_produce_message_conversions_time_ms_average\",",
            "          \"refId\": \"A\",",
            "          \"legendFormat\": \"{{name}} - avg\"",
            "        }, {",
            "          \"expr\": \"aws_kafka_produce_message_conversions_time_ms_maximum\",",
            "          \"refId\": \"B\",",
            "          \"legendFormat\": \"{{name}} - max\"",
            "        }],",
            "        \"options\": {\"legend\": {\"displayMode\": \"table\", \"placement\": \"bottom\"}},",
            "        \"fieldConfig\": {",
            "          \"defaults\": {",
            "            \"unit\": \"ms\",",
            "            \"color\": {\"mode\": \"palette-classic\"}",
            "          }",
            "        }",
            "      },",
            "      {",
            "        \"type\": \"row\",",
            "        \"title\": \"Network Health\",",
            "        \"gridPos\": {\"x\": 0, \"y\": 43, \"w\": 24, \"h\": 1},",
            "        \"collapsed\": false",
            "      },",
            "      {",
            "        \"type\": \"stat\",",
            "        \"title\": \"Network RX Errors\",",
            "        \"gridPos\": {\"x\": 0, \"y\": 44, \"w\": 6, \"h\": 4},",
            "        \"targets\": [{",
            "          \"expr\": \"sum(aws_kafka_network_rx_errors_sum)\",",
            "          \"refId\": \"A\"",
            "        }],",
            "        \"options\": {\"graphMode\": \"area\", \"colorMode\": \"value\"},",
            "        \"fieldConfig\": {",
            "          \"defaults\": {",
            "            \"unit\": \"short\",",
            "            \"thresholds\": {",
            "              \"mode\": \"absolute\",",
            "              \"steps\": [",
            "                {\"value\": 0, \"color\": \"green\"},",
            "                {\"value\": 1, \"color\": \"yellow\"},",
            "                {\"value\": 100, \"color\": \"red\"}",
            "              ]",
            "            }",
            "          }",
            "        }",
            "      },",
            "      {",
            "        \"type\": \"stat\",",
            "        \"title\": \"Network TX Errors\",",
            "        \"gridPos\": {\"x\": 6, \"y\": 44, \"w\": 6, \"h\": 4},",
            "        \"targets\": [{",
            "          \"expr\": \"sum(aws_kafka_network_tx_errors_sum)\",",
            "          \"refId\": \"A\"",
            "        }],",
            "        \"options\": {\"graphMode\": \"area\", \"colorMode\": \"value\"},",
            "        \"fieldConfig\": {",
            "          \"defaults\": {",
            "            \"unit\": \"short\",",
            "            \"thresholds\": {",
            "              \"mode\": \"absolute\",",
            "              \"steps\": [",
            "                {\"value\": 0, \"color\": \"green\"},",
            "                {\"value\": 1, \"color\": \"yellow\"},",
            "                {\"value\": 100, \"color\": \"red\"}",
            "              ]",
            "            }",
            "          }",
            "        }",
            "      },",
            "      {",
            "        \"type\": \"timeseries\",",
            "        \"title\": \"Network Errors Over Time\",",
            "        \"gridPos\": {\"x\": 12, \"y\": 44, \"w\": 12, \"h\": 8},",
            "        \"targets\": [",
            "          {",
            "            \"expr\": \"aws_kafka_network_rx_errors_sum\",",
            "            \"refId\": \"A\",",
            "            \"legendFormat\": \"{{name}} - RX Errors\"",
            "          },",
            "          {",
            "            \"expr\": \"aws_kafka_network_tx_errors_sum\",",
            "            \"refId\": \"B\",",
            "            \"legendFormat\": \"{{name}} - TX Errors\"",
            "          }",
            "        ],",
            "        \"options\": {\"legend\": {\"displayMode\": \"table\", \"placement\": \"bottom\"}},",
            "        \"fieldConfig\": {",
            "          \"defaults\": {",
            "            \"unit\": \"short\",",
            "            \"color\": {\"mode\": \"palette-classic\"}",
            "          }",
            "        }",
            "      }",
            "    ]",
            "  },",
            "  \"overwrite\": true",
            "}",
            "DASH_EOF",
            "",
            "echo \"[Grafana] Importing MSK Kafka dashboard\"",
            "curl -X POST -H \"Content-Type: application/json\" \\",
            "  -u \"admin:$GRAFANA_PASSWORD\" \\",
            "  \"$API_URL/dashboards/db\" \\",
            "  -d @/tmp/kafka-dashboard.json",
            "",
            "echo \"\"",
            "kill $PF_PID 2>/dev/null || true",
            "",
            "echo \"[Grafana] MSK Kafka dashboard configuration complete\"",
            "echo \"[Grafana] Dashboard available at: Dashboards -> MSK Kafka Monitoring\""
          ]
        }
      }
    ]
  })

  tags = {
    Tenant    = local.effective_tenant
    Env       = local.primary_env
    Name      = "${lower(local.effective_tenant)}-${local.primary_env}-grafana-kafka-dashboard"
    Component = "Monitoring"
  }
}

resource "aws_ssm_association" "grafana_kafka_dashboard" {
  count = local.karpenter_enabled ? 1 : 0
  name  = aws_ssm_document.grafana_kafka_dashboard.name

  targets {
    key    = "tag:Name"
    values = ["${lower(local.effective_tenant)}-${local.effective_region}-bastion"]
  }

  parameters = {
    ClusterName = module.envs[local.primary_env].eks_cluster_name
    Region      = local.effective_region
  }

  depends_on = [
    module.envs,
    aws_ssm_association.install_prometheus,
    aws_ssm_association.install_yace,
    aws_ssm_association.grafana_dashboards
  ]
}
