resource "aws_ssm_document" "deploy_yace" {
  for_each = toset(local.enabled_environments)

  name          = "${lower(local.effective_tenant)}-${each.key}-deploy-yace"
  document_type = "Command"

  content = jsonencode({
    schemaVersion = "2.2",
    description   = "Deploy YACE CloudWatch exporter to monitoring namespace",
    parameters = {
      Environment = {
        type        = "String"
        description = "Environment name (prod, dev, etc.)"
      }
      Namespace = {
        type    = "String"
        default = "monitoring"
      }
    },
    mainSteps = [
      {
        action = "aws:runShellScript",
        name   = "DeployYACE",
        inputs = {
          runCommand = [
            "set -eo pipefail",
            "exec 2>&1",

            "ENV='{{ Environment }}'",
            "NS='{{ Namespace }}'",
            "echo \"[$(date '+%Y-%m-%d %H:%M:%S')] Deploying YACE for environment: $${ENV}\"",

            "REGION=$(aws ssm get-parameter --name /terraform/shared/region --query 'Parameter.Value' --output text 2>/dev/null || echo 'us-east-1')",
            "CLUSTER=$(aws ssm get-parameter --name /terraform/envs/$${ENV}/cluster_name --query 'Parameter.Value' --output text --region $${REGION})",
            "YACE_ROLE_ARN=$(aws ssm get-parameter --name /eks/$${CLUSTER}/monitoring/yace_role_arn --query 'Parameter.Value' --output text --region $${REGION})",
            "KAFKA_ENABLED=$(aws ssm get-parameter --name /terraform/envs/$${ENV}/kafka_enabled --query 'Parameter.Value' --output text --region $${REGION} 2>/dev/null || echo 'false')",

            "echo \"Configuration:\"",
            "echo \"  Region: $${REGION}\"",
            "echo \"  Cluster: $${CLUSTER}\"",
            "echo \"  YACE Role ARN: $${YACE_ROLE_ARN}\"",
            "echo \"  Kafka Enabled: $${KAFKA_ENABLED}\"",

            "export AWS_REGION=\"$${REGION}\" AWS_DEFAULT_REGION=\"$${REGION}\"",
            "export HOME=/root",
            "mkdir -p /root/.kube",
            "export KUBECONFIG=/root/.kube/config",
            "set -u",

            "aws eks update-kubeconfig --region \"$REGION\" --name \"$CLUSTER\" --alias \"$CLUSTER\" --kubeconfig \"$KUBECONFIG\"",

            "kubectl get namespace \"$${NS}\" 2>/dev/null || kubectl create namespace \"$${NS}\"",

            "echo \"[$(date '+%Y-%m-%d %H:%M:%S')] Applying YACE manifests...\"",

            "cat <<EOF | kubectl apply -f -",
            "apiVersion: v1",
            "kind: ServiceAccount",
            "metadata:",
            "  name: yace-exporter",
            "  namespace: $${NS}",
            "  annotations:",
            "    eks.amazonaws.com/role-arn: $${YACE_ROLE_ARN}",
            "EOF",

            "# Build YACE config dynamically based on Kafka enablement",
            "cat > /tmp/yace-configmap.yaml <<CONFIGMAP_START",
            "apiVersion: v1",
            "kind: ConfigMap",
            "metadata:",
            "  name: yace-config",
            "  namespace: $${NS}",
            "data:",
            "  config.yml: |",
            "    apiVersion: v1alpha1",
            "    sts-region: $${REGION}",
            "    discovery:",
            "      exportedTagsOnMetrics:",
            "        rds:",
            "          - Name",
            "          - Env",
            "CONFIGMAP_START",
            "",
            "# Add Kafka to exportedTagsOnMetrics if enabled",
            "if [ \"$${KAFKA_ENABLED}\" = \"true\" ]; then",
            "  cat >> /tmp/yace-configmap.yaml <<'KAFKA_TAGS'",
            "        kafka:",
            "          - Name",
            "          - Env",
            "KAFKA_TAGS",
            "fi",
            "",
            "# Add RDS discovery job",
            "cat >> /tmp/yace-configmap.yaml <<EOF",
            "      jobs:",
            "        - type: rds",
            "          regions:",
            "            - $${REGION}",
            "          searchTags:",
            "            - key: Env",
            "              value: $${ENV}",
            "          metrics:",
            "            - name: CPUUtilization",
            "              statistics: [Average, Maximum]",
            "              period: 300",
            "              length: 600",
            "            - name: DatabaseConnections",
            "              statistics: [Average, Maximum]",
            "              period: 300",
            "              length: 600",
            "            - name: FreeableMemory",
            "              statistics: [Average]",
            "              period: 300",
            "              length: 600",
            "            - name: FreeStorageSpace",
            "              statistics: [Average]",
            "              period: 300",
            "              length: 600",
            "            - name: ReadLatency",
            "              statistics: [Average]",
            "              period: 300",
            "              length: 600",
            "            - name: WriteLatency",
            "              statistics: [Average]",
            "              period: 300",
            "              length: 600",
            "            - name: ACUUtilization",
            "              statistics: [Average, Maximum]",
            "              period: 300",
            "              length: 600",
            "            - name: ServerlessDatabaseCapacity",
            "              statistics: [Average, Maximum]",
            "              period: 300",
            "              length: 600",
            "            - name: Deadlocks",
            "              statistics: [Sum]",
            "              period: 300",
            "              length: 600",
            "            - name: NetworkReceiveThroughput",
            "              statistics: [Average]",
            "              period: 300",
            "              length: 600",
            "            - name: NetworkTransmitThroughput",
            "              statistics: [Average]",
            "              period: 300",
            "              length: 600",
            "            - name: ReadThroughput",
            "              statistics: [Average]",
            "              period: 300",
            "              length: 600",
            "            - name: WriteThroughput",
            "              statistics: [Average]",
            "              period: 300",
            "              length: 600",
            "            - name: ReadIOPS",
            "              statistics: [Average]",
            "              period: 300",
            "              length: 600",
            "            - name: WriteIOPS",
            "              statistics: [Average]",
            "              period: 300",
            "              length: 600",
            "            - name: DiskQueueDepth",
            "              statistics: [Average]",
            "              period: 300",
            "              length: 600",
            "            - name: BufferCacheHitRatio",
            "              statistics: [Average]",
            "              period: 300",
            "              length: 600",
            "            - name: DatabaseMemoryUsagePercentage",
            "              statistics: [Average, Maximum]",
            "              period: 300",
            "              length: 600",
            "            - name: AuroraReplicaLag",
            "              statistics: [Average, Maximum]",
            "              period: 300",
            "              length: 600",
            "EOF",
            "",
            "# Add Kafka discovery job if enabled",
            "if [ \"$${KAFKA_ENABLED}\" = \"true\" ]; then",
            "  cat >> /tmp/yace-configmap.yaml <<EOF",
            "        - type: kafka",
            "          regions:",
            "            - $${REGION}",
            "          searchTags:",
            "            - key: Env",
            "              value: $${ENV}",
            "          metrics:",
            "            - name: CpuUser",
            "              statistics: [Average]",
            "              period: 300",
            "              length: 600",
            "            - name: MemoryUsed",
            "              statistics: [Average]",
            "              period: 300",
            "              length: 600",
            "            - name: KafkaDataLogsDiskUsed",
            "              statistics: [Average]",
            "              period: 300",
            "              length: 600",
            "            - name: BytesInPerSec",
            "              statistics: [Sum]",
            "              period: 300",
            "              length: 600",
            "            - name: BytesOutPerSec",
            "              statistics: [Sum]",
            "              period: 300",
            "              length: 600",
            "EOF",
            "fi",
            "",
            "# Add static ElastiCache config",
            "cat >> /tmp/yace-configmap.yaml <<EOF",
            "    static:",
            "      - namespace: AWS/ElastiCache",
            "        name: ria-$${ENV}-redis",
            "        regions:",
            "          - $${REGION}",
            "        dimensions:",
            "          - name: CacheClusterId",
            "            value: ria-$${ENV}-redis-001",
            "        customTags:",
            "          - key: Env",
            "            value: $${ENV}",
            "          - key: Name",
            "            value: ria-$${ENV}-redis",
            "        metrics:",
            "          - name: CPUUtilization",
            "            statistics: [Average]",
            "            period: 300",
            "            length: 600",
            "          - name: NetworkBytesIn",
            "            statistics: [Sum]",
            "            period: 300",
            "            length: 600",
            "          - name: NetworkBytesOut",
            "            statistics: [Sum]",
            "            period: 300",
            "            length: 600",
            "          - name: CurrConnections",
            "            statistics: [Average]",
            "            period: 300",
            "            length: 600",
            "          - name: CacheHits",
            "            statistics: [Sum, Average]",
            "            period: 300",
            "            length: 600",
            "          - name: CacheMisses",
            "            statistics: [Sum, Average]",
            "            period: 300",
            "            length: 600",
            "          - name: Evictions",
            "            statistics: [Sum, Average]",
            "            period: 300",
            "            length: 600",
            "          - name: DatabaseMemoryUsagePercentage",
            "            statistics: [Average, Maximum]",
            "            period: 300",
            "            length: 600",
            "EOF",
            "",
            "# Apply the ConfigMap",
            "kubectl apply -f /tmp/yace-configmap.yaml",

            "cat <<EOF | kubectl apply -f -",
            "apiVersion: apps/v1",
            "kind: Deployment",
            "metadata:",
            "  name: yace-exporter",
            "  namespace: $${NS}",
            "  labels:",
            "    app: yace-exporter",
            "spec:",
            "  replicas: 1",
            "  selector:",
            "    matchLabels:",
            "      app: yace-exporter",
            "  template:",
            "    metadata:",
            "      labels:",
            "        app: yace-exporter",
            "    spec:",
            "      serviceAccountName: yace-exporter",
            "      containers:",
            "        - name: yace",
            "          image: ghcr.io/nerdswords/yet-another-cloudwatch-exporter:v0.58.0",
            "          ports:",
            "            - name: metrics",
            "              containerPort: 5000",
            "              protocol: TCP",
            "          env:",
            "            - name: AWS_REGION",
            "              value: $${REGION}",
            "          volumeMounts:",
            "            - name: config",
            "              mountPath: /tmp/config.yml",
            "              subPath: config.yml",
            "          resources:",
            "            requests:",
            "              cpu: 100m",
            "              memory: 256Mi",
            "            limits:",
            "              cpu: 500m",
            "              memory: 512Mi",
            "      volumes:",
            "        - name: config",
            "          configMap:",
            "            name: yace-config",
            "EOF",

            "cat <<EOF | kubectl apply -f -",
            "apiVersion: v1",
            "kind: Service",
            "metadata:",
            "  name: yace-exporter",
            "  namespace: $${NS}",
            "  labels:",
            "    app: yace-exporter",
            "spec:",
            "  type: ClusterIP",
            "  ports:",
            "    - port: 5000",
            "      targetPort: metrics",
            "      protocol: TCP",
            "      name: metrics",
            "  selector:",
            "    app: yace-exporter",
            "EOF",

            "cat <<EOF | kubectl apply -f -",
            "apiVersion: monitoring.coreos.com/v1",
            "kind: ServiceMonitor",
            "metadata:",
            "  name: yace-exporter",
            "  namespace: $${NS}",
            "  labels:",
            "    app: yace-exporter",
            "    release: kube-prometheus-stack",
            "spec:",
            "  selector:",
            "    matchLabels:",
            "      app: yace-exporter",
            "  endpoints:",
            "    - port: metrics",
            "      interval: 60s",
            "      scrapeTimeout: 30s",
            "      path: /metrics",
            "EOF",

            "echo \"[$(date '+%Y-%m-%d %H:%M:%S')] YACE deployment complete\"",
            "kubectl -n \"$${NS}\" get deployment yace-exporter",
            "kubectl -n \"$${NS}\" get svc yace-exporter",
            "kubectl -n \"$${NS}\" get servicemonitor yace-exporter",
          ]
        }
      }
    ]
  })
}

resource "aws_ssm_association" "deploy_yace" {
  for_each = toset(local.enabled_environments)

  name = aws_ssm_document.deploy_yace[each.key].name

  targets {
    key    = "tag:Environment"
    values = [each.key]
  }

  parameters = {
    Environment = each.key
    Namespace   = "monitoring"
  }

  depends_on = [
    module.envs,
    aws_ssm_document.deploy_yace,
  ]
}
