# ============================================
# ssm-grafana-dashboards.tf
# SSM Document to create minimal health dashboard
# ============================================

resource "aws_ssm_document" "grafana_dashboards" {
  name            = "${lower(local.effective_tenant)}-${local.primary_env}-grafana-dashboards"
  document_type   = "Command"
  document_format = "YAML"

  content = yamlencode({
    schemaVersion = "2.2"
    description   = "Configure self-hosted Grafana with minimal health-focused dashboard"
    parameters = {
      Region = {
        type        = "String"
        description = "AWS Region"
        default     = local.effective_region
      }
      ClusterName = {
        type        = "String"
        description = "EKS Cluster Name"
      }
    }
    mainSteps = [
      {
        action = "aws:runShellScript"
        name   = "configureGrafanaDashboard"
        inputs = {
          runCommand = [
            "#!/bin/bash",
            "set -e",
            "",
            "CLUSTER_NAME='{{ ClusterName }}'",
            "REGION='{{ Region }}'",
            "",
            "export HOME=/root",
            "export KUBECONFIG=/root/.kube/config",
            "export AWS_REGION=\"$REGION\" AWS_DEFAULT_REGION=\"$REGION\"",
            "",
            "echo \"[Grafana] Configuring dashboard in self-hosted Grafana\"",
            "",
            "aws eks update-kubeconfig --name \"$CLUSTER_NAME\" --region \"$REGION\" --kubeconfig \"$KUBECONFIG\"",
            "",
            "POD_NAME=$(kubectl get pods -n monitoring -l app.kubernetes.io/name=grafana -o jsonpath='{.items[0].metadata.name}')",
            "if [ -z \"$POD_NAME\" ]; then",
            "  echo \"[ERROR] Grafana pod not found\"",
            "  exit 1",
            "fi",
            "",
            "echo \"[Grafana] Found Grafana pod: $POD_NAME\"",
            "",
            "GRAFANA_PASSWORD=$(kubectl get secret -n monitoring prometheus-grafana -o jsonpath='{.data.admin-password}' | base64 -d)",
            "",
            "echo \"[Grafana] Port-forwarding to Grafana (background)\"",
            "kubectl port-forward -n monitoring \"$POD_NAME\" 3000:3000 &",
            "PF_PID=$!",
            "sleep 5",
            "",
            "API_URL='http://localhost:3000/api'",
            "",
            "echo \"[Grafana] Creating Health Status dashboard\"",
            "cat > /tmp/health-dashboard.json <<'DASH_EOF'",
            "{",
            "  \"dashboard\": {",
            "    \"title\": \"Cluster Health Status\",",
            "    \"tags\": [\"health\", \"status\"],",
            "    \"timezone\": \"browser\",",
            "    \"schemaVersion\": 16,",
            "    \"version\": 0,",
            "    \"refresh\": \"30s\",",
            "    \"panels\": [",
            "      {",
            "        \"type\": \"stat\",",
            "        \"title\": \"Cluster Status\",",
            "        \"gridPos\": {\"x\": 0, \"y\": 0, \"w\": 6, \"h\": 4},",
            "        \"targets\": [{",
            "          \"expr\": \"up{job='kube-state-metrics'}\",",
            "          \"refId\": \"A\"",
            "        }],",
            "        \"options\": {",
            "          \"graphMode\": \"none\",",
            "          \"colorMode\": \"value\",",
            "          \"textMode\": \"value_and_name\"",
            "        },",
            "        \"fieldConfig\": {",
            "          \"defaults\": {",
            "            \"mappings\": [{",
            "              \"type\": \"value\",",
            "              \"options\": {",
            "                \"1\": {\"text\": \"HEALTHY\", \"color\": \"green\"},",
            "                \"0\": {\"text\": \"DOWN\", \"color\": \"red\"}",
            "              }",
            "            }],",
            "            \"thresholds\": {",
            "              \"mode\": \"absolute\",",
            "              \"steps\": [",
            "                {\"value\": 0, \"color\": \"red\"},",
            "                {\"value\": 1, \"color\": \"green\"}",
            "              ]",
            "            }",
            "          }",
            "        }",
            "      },",
            "      {",
            "        \"type\": \"stat\",",
            "        \"title\": \"Total Nodes\",",
            "        \"gridPos\": {\"x\": 6, \"y\": 0, \"w\": 6, \"h\": 4},",
            "        \"targets\": [{",
            "          \"expr\": \"count(kube_node_info)\",",
            "          \"refId\": \"A\"",
            "        }],",
            "        \"options\": {\"graphMode\": \"none\", \"colorMode\": \"value\"}",
            "      },",
            "      {",
            "        \"type\": \"stat\",",
            "        \"title\": \"Ready Nodes\",",
            "        \"gridPos\": {\"x\": 12, \"y\": 0, \"w\": 6, \"h\": 4},",
            "        \"targets\": [{",
            "          \"expr\": \"sum(kube_node_status_condition{condition='Ready',status='true'})\",",
            "          \"refId\": \"A\"",
            "        }],",
            "        \"options\": {\"graphMode\": \"none\", \"colorMode\": \"value\"}",
            "      },",
            "      {",
            "        \"type\": \"stat\",",
            "        \"title\": \"Unhealthy Pods\",",
            "        \"gridPos\": {\"x\": 18, \"y\": 0, \"w\": 6, \"h\": 4},",
            "        \"targets\": [{",
            "          \"expr\": \"count(kube_pod_status_phase{phase!='Running',phase!='Succeeded'}) OR on() vector(0)\",",
            "          \"refId\": \"A\"",
            "        }],",
            "        \"options\": {\"graphMode\": \"none\", \"colorMode\": \"value\"},",
            "        \"fieldConfig\": {",
            "          \"defaults\": {",
            "            \"thresholds\": {",
            "              \"mode\": \"absolute\",",
            "              \"steps\": [",
            "                {\"value\": 0, \"color\": \"green\"},",
            "                {\"value\": 1, \"color\": \"yellow\"},",
            "                {\"value\": 5, \"color\": \"red\"}",
            "              ]",
            "            }",
            "          }",
            "        }",
            "      },",
            "      {",
            "        \"type\": \"timeseries\",",
            "        \"title\": \"Cluster CPU Usage (Last 7 Days)\",",
            "        \"gridPos\": {\"x\": 0, \"y\": 4, \"w\": 12, \"h\": 8},",
            "        \"targets\": [{",
            "          \"expr\": \"sum(rate(container_cpu_usage_seconds_total{container!=\\\"\\\"}[5m])) / sum(machine_cpu_cores) * 100\",",
            "          \"refId\": \"A\",",
            "          \"legendFormat\": \"CPU %\"",
            "        }],",
            "        \"options\": {\"legend\": {\"displayMode\": \"list\", \"placement\": \"bottom\"}},",
            "        \"fieldConfig\": {\"defaults\": {\"unit\": \"percent\", \"min\": 0, \"max\": 100}}",
            "      },",
            "      {",
            "        \"type\": \"timeseries\",",
            "        \"title\": \"Cluster Memory Usage (Last 7 Days)\",",
            "        \"gridPos\": {\"x\": 12, \"y\": 4, \"w\": 12, \"h\": 8},",
            "        \"targets\": [{",
            "          \"expr\": \"sum(container_memory_working_set_bytes{container!=\\\"\\\"}) / sum(machine_memory_bytes) * 100\",",
            "          \"refId\": \"A\",",
            "          \"legendFormat\": \"Memory %\"",
            "        }],",
            "        \"options\": {\"legend\": {\"displayMode\": \"list\", \"placement\": \"bottom\"}},",
            "        \"fieldConfig\": {\"defaults\": {\"unit\": \"percent\", \"min\": 0, \"max\": 100}}",
            "      },",
            "      {",
            "        \"type\": \"stat\",",
            "        \"title\": \"RDS CPU Utilization\",",
            "        \"gridPos\": {\"x\": 0, \"y\": 12, \"w\": 6, \"h\": 4},",
            "        \"targets\": [{",
            "          \"expr\": \"aws_rds_cpuutilization_average\",",
            "          \"refId\": \"A\"",
            "        }],",
            "        \"options\": {\"graphMode\": \"area\", \"colorMode\": \"value\"},",
            "        \"fieldConfig\": {",
            "          \"defaults\": {",
            "            \"unit\": \"percent\",",
            "            \"thresholds\": {",
            "              \"mode\": \"absolute\",",
            "              \"steps\": [",
            "                {\"value\": 0, \"color\": \"green\"},",
            "                {\"value\": 70, \"color\": \"yellow\"},",
            "                {\"value\": 85, \"color\": \"red\"}",
            "              ]",
            "            }",
            "          }",
            "        }",
            "      },",
            "      {",
            "        \"type\": \"stat\",",
            "        \"title\": \"RDS Connections\",",
            "        \"gridPos\": {\"x\": 6, \"y\": 12, \"w\": 6, \"h\": 4},",
            "        \"targets\": [{",
            "          \"expr\": \"aws_rds_database_connections_average\",",
            "          \"refId\": \"A\"",
            "        }],",
            "        \"options\": {\"graphMode\": \"area\", \"colorMode\": \"value\"},",
            "        \"fieldConfig\": {\"defaults\": {\"unit\": \"short\"}}",
            "      },",
            "      {",
            "        \"type\": \"stat\",",
            "        \"title\": \"RDS Free Storage\",",
            "        \"gridPos\": {\"x\": 12, \"y\": 12, \"w\": 6, \"h\": 4},",
            "        \"targets\": [{",
            "          \"expr\": \"aws_rds_free_storage_space_average / 1024 / 1024 / 1024\",",
            "          \"refId\": \"A\"",
            "        }],",
            "        \"options\": {\"graphMode\": \"area\", \"colorMode\": \"value\"},",
            "        \"fieldConfig\": {",
            "          \"defaults\": {",
            "            \"unit\": \"decgbytes\",",
            "            \"thresholds\": {",
            "              \"mode\": \"absolute\",",
            "              \"steps\": [",
            "                {\"value\": 0, \"color\": \"red\"},",
            "                {\"value\": 10, \"color\": \"yellow\"},",
            "                {\"value\": 50, \"color\": \"green\"}",
            "              ]",
            "            }",
            "          }",
            "        }",
            "      },",
            "      {",
            "        \"type\": \"stat\",",
            "        \"title\": \"RDS Free Memory\",",
            "        \"gridPos\": {\"x\": 18, \"y\": 12, \"w\": 6, \"h\": 4},",
            "        \"targets\": [{",
            "          \"expr\": \"aws_rds_freeable_memory_average / 1024 / 1024 / 1024\",",
            "          \"refId\": \"A\"",
            "        }],",
            "        \"options\": {\"graphMode\": \"area\", \"colorMode\": \"value\"},",
            "        \"fieldConfig\": {\"defaults\": {\"unit\": \"decgbytes\"}}",
            "      },",
            "      {",
            "        \"type\": \"timeseries\",",
            "        \"title\": \"RDS IOPS (Last 7 Days)\",",
            "        \"gridPos\": {\"x\": 0, \"y\": 16, \"w\": 12, \"h\": 8},",
            "        \"targets\": [",
            "          {",
            "            \"expr\": \"aws_rds_read_iops_average\",",
            "            \"refId\": \"A\",",
            "            \"legendFormat\": \"Read IOPS\"",
            "          },",
            "          {",
            "            \"expr\": \"aws_rds_write_iops_average\",",
            "            \"refId\": \"B\",",
            "            \"legendFormat\": \"Write IOPS\"",
            "          }",
            "        ],",
            "        \"options\": {\"legend\": {\"displayMode\": \"list\", \"placement\": \"bottom\"}},",
            "        \"fieldConfig\": {\"defaults\": {\"unit\": \"iops\"}}",
            "      },",
            "      {",
            "        \"type\": \"timeseries\",",
            "        \"title\": \"RDS Latency (Last 7 Days)\",",
            "        \"gridPos\": {\"x\": 12, \"y\": 16, \"w\": 12, \"h\": 8},",
            "        \"targets\": [",
            "          {",
            "            \"expr\": \"aws_rds_read_latency_average * 1000\",",
            "            \"refId\": \"A\",",
            "            \"legendFormat\": \"Read Latency\"",
            "          },",
            "          {",
            "            \"expr\": \"aws_rds_write_latency_average * 1000\",",
            "            \"refId\": \"B\",",
            "            \"legendFormat\": \"Write Latency\"",
            "          }",
            "        ],",
            "        \"options\": {\"legend\": {\"displayMode\": \"list\", \"placement\": \"bottom\"}},",
            "        \"fieldConfig\": {\"defaults\": {\"unit\": \"ms\"}}",
            "      }",
            "    ]",
            "  },",
            "  \"overwrite\": true",
            "}",
            "DASH_EOF",
            "",
            "echo \"[Grafana] Importing dashboard\"",
            "curl -X POST -H \"Content-Type: application/json\" \\",
            "  -u \"admin:$GRAFANA_PASSWORD\" \\",
            "  \"$API_URL/dashboards/db\" \\",
            "  -d @/tmp/health-dashboard.json",
            "",
            "echo \"\"",
            "echo \"[Grafana] Setting dashboard as home dashboard\"",
            "DASH_UID=$(curl -s -u \"admin:$GRAFANA_PASSWORD\" \"$API_URL/dashboards/uid/cluster-health-status\" | jq -r '.dashboard.uid')",
            "",
            "curl -X PUT -H \"Content-Type: application/json\" \\",
            "  -u \"admin:$GRAFANA_PASSWORD\" \\",
            "  \"$API_URL/org/preferences\" \\",
            "  -d \"{\\\"homeDashboardUID\\\": \\\"$DASH_UID\\\"}\"",
            "",
            "echo \"\"",
            "kill $PF_PID 2>/dev/null || true",
            "",
            "echo \"[Grafana] Dashboard configuration complete\"",
            "echo \"[Grafana] Access Grafana via port-forward: kubectl port-forward -n monitoring svc/prometheus-grafana 3000:80\"",
            "echo \"[Grafana] Username: admin\"",
            "echo \"[Grafana] Password stored in: /eks/$CLUSTER_NAME/monitoring/grafana_password\""
          ]
        }
      }
    ]
  })

  tags = {
    Tenant   = local.effective_tenant
    Env      = local.primary_env
    Name     = "${lower(local.effective_tenant)}-${local.primary_env}-grafana-dashboards"
    Component = "Monitoring"
  }
}

resource "aws_ssm_association" "grafana_dashboards" {
  count = local.karpenter_enabled ? 1 : 0
  name  = aws_ssm_document.grafana_dashboards.name

  targets {
    key    = "tag:Name"
    values = ["${lower(local.effective_tenant)}-${local.effective_region}-bastion"]
  }

  parameters = {
    ClusterName = module.envs[local.primary_env].eks_cluster_name
    Region      = local.effective_region
  }

  depends_on = [
    module.envs,
    aws_ssm_association.install_prometheus,
    aws_ssm_association.install_yace
  ]
}
