apiVersion: v1
kind: Service
metadata:
  name: alertmanager-sns-forwarder
  namespace: monitoring
  labels:
    app: alertmanager-sns-forwarder
spec:
  type: ClusterIP
  ports:
    - port: 9087
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    app: alertmanager-sns-forwarder
