apiVersion: v1
kind: Service
metadata:
  name: yace-exporter
  namespace: monitoring
  labels:
    app: yace-exporter
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: yace-exporter
